site_name: "NUCT_API_WRAPPER"
theme:
  name: "material"

nav:
  - HOME: index.md
  - DOCS: 
    - NUCT: nuct.md
    - 課題：Assignment: assignment.md
    - お知らせ：Announcement: announcement.md
    - リソース：Content: content.md
    - 小テスト：Quiz: quiz.md
    - 参加者：Roster: roster.md

plugins:
- search
- mkdocstrings:
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
