site_name: "NUCT_API_WRAPPER"
theme:
  name: "material"

nav:
  - HOME: index.md
  - DOCS: docs/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav-file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
